sudo: false

language: ruby
rvm: 2.3.1
cache: bundler

branches:
  only:
  - master

script:
- bundle exec jekyll build --config _config.yml,_test_config.yml
- bundle exec jekyll build --config _config.yml,_test_config.yml
- ls -lah /home/travis/build/julien-hadleyjack/cooking-recipes/images/
- ls -lah /home/travis/build/julien-hadleyjack/cooking-recipes/images/thumbnail/
- ls -lah /home/travis/build/julien-hadleyjack/cooking-recipes/_site/images/
- bundle exec htmlproofer ./_site --disable-external
- bundle exec jekyll clean
- bundle exec jekyll build


after_success:
- git clone https://$GH_REF ${TARGET_BRANCH}
- cd ${TARGET_BRANCH}
- ls -lah
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- git config push.default simple
- git checkout -f ${TARGET_BRANCH}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git status
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "https://${DEPLOY_KEY}@${GH_REF}" ${TARGET_BRANCH} > /dev/null 2>&1

addons:
  apt:
    packages:
    - libmagic-dev
    
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
  - GH_REF=github.com/julien-hadleyjack/cooking-recipes
  - EMAIL=github@jlhj.de
  - TARGET_BRANCH=gh-pages
  - secure: 0XAnvx/lB49nDupzLjSeU8HTwXz1hSR1DoRcx0CxPhXWMXyOS6Frz7hQmZFOjecKUFVTLmhpN4n/1ih5jDqkp64RDTm3lVr2wSQ/mYUNOUgpKnK5gOUxpSEu+3NYUvBKLxuMyTQCb5gyz7tKdSqhkFZNbX7L4+oGM6N4kchIbHY1Q21viObtnZCGr6Xo7hm2e4zIRC8DMrb4Upl+k9R7Xpy9xLy1UHibcEBIf4ynJdNQ3J9plDbD0awXqKC1bZchsxN7sO+FhJoQALQSBxmhJRZma9ib9pR8i+sHxGsftpFkb6CGz9HW99xYE8zD8PWB+MB3XkyDGveKkFHD2Trql3jptp+D6bOV29T7jaOEBWLrz+AuAugBu0nB7r/DUlZ6lnH84Yg0QIGgtx5NujUTmC7pl13EE4xuYUvS6Q/MrqxdbsyOnVeTurcaY/HgnI9tRQnqrR8h0wfnTEnZu6ZIt2W4HcJgE0n3UiILPx80d8RwS9y53cG5ZGI2aNc6+iiAAc9msfQjTyUk502v6jsR/O30miX4SeHjSCBNfACmMU8BL9+ADQhUQUCn/VwsPAWsTq+p4p5nI+NdOlkvSMeLBfcZPgdiDaLmcN24qRxMisKevuz1hDr40q0td/HHL4SxeL+9kSGGuxeHnsifSqq3f82MxwaE1ICCVC1tLWbUO40=
