sudo: false

language: ruby
rvm: 2.3.1

branches:
  only:
  - master

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external

#after_success:
#- git clone https://$GH_REF
#- cd $(basename ${GH_REF%.git})
#- git config user.name "Travis-CI"
#- git config user.email ${EMAIL}
#- rsync -az --delete --exclude '.git*' ../_site/ .
#- touch .nojekyll
#- git add -A .
#- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
#- git push -f "https://${DEPLOY_KEY}@${GH_REF}" ${TARGET_BRANCH} > /dev/null 2>&1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: https://github.com/julien-hadleyjack/cooking-recipes
  - EMAIL: github@jlhj.de
  - TARGET_BRANCH: gh-pages