sudo: false

language: ruby
rvm: 2.3.1
cache: bundler

branches:
  only: master

script:
- bundle exec jekyll build --config _config.yml,_test_config.yml
- bundle exec htmlproofer ./_site --disable-external
- bundle exec jekyll clean
- bundle exec jekyll build


after_success:
- openssl aes-256-cbc -K $encrypted_6fb170b23217_key -iv $encrypted_6fb170b23217_iv -in github_deploy_key.enc -out github_deploy_key -d
- |
   # https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md
   declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
   openssl aes-256-cbc \
     -K $encrypted_6fb170b23217_key \
     -iv $encrypted_6fb170b23217_iv \
     -in "github_deploy_key.enc" \
     -out "$SSH_FILE" -d

   # Enable SSH authentication
   chmod 600 "$SSH_FILE" \
     && printf "%s\n" \
          "Host github.com" \
          "  IdentityFile $SSH_FILE" \
          "  LogLevel ERROR" >> ~/.ssh/config
- git clone "${GH_REF}" ${TARGET_BRANCH}
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- git config push.default simple
- cd ${TARGET_BRANCH}
- ls -lah
- git checkout -f ${TARGET_BRANCH}
- rsync -az --delete --exclude '.git*' --exclude 'github_deploy_key' ../_site/ .
- touch .nojekyll
- git add -A .
- git status
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "${GH_REF}" ${TARGET_BRANCH}

addons:
  apt:
    packages:
    - libmagic-dev
    
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production
  - GH_REF=git@github.com:julien-hadleyjack/cooking-recipes.git
  - EMAIL=github@jlhj.de
  - TARGET_BRANCH=gh-pages