20-minuten-sind-genug:
  title: 20 Minuten sind genug
basic-cooking:
  title: Basic Cooking
basic-cooking-2:
  title: Basic Cooking 2
crashkurs-kochen:
  title: "Crashkurs: Kochen"
lunch-im-glas:
  title: Lunch im Glas
natuerlich-essen:
  title: Natürlich Essen
one-pot-pasta:
  title: One Pot Pasta