---
header:
  teaser: thumbnail/girandole-ai-funghi-con-pancetta.jpg
gallery:
  - url: girandole-ai-funghi-con-pancetta.jpg
    image_path: thumbnail/girandole-ai-funghi-con-pancetta.jpg
---
= Girandole ai Funghi con Pancetta
:page-layout: single
:epub-picture: girandole-ai-funghi-con-pancetta.jpg
:page-liquid:

**Quelle**: One Pot Pasta, S. 22

**Zubereitungszeit**: 35 min

**Personen**: 2


== Zutaten
:hardbreaks:

**Gemüse/Obst/frische Gewürze**
5 g getrocknete Steinpilze
250 g Champignons
1 Zweig Rosmarin
4 Stiele Petersilie
1 Schalotte
1 Knoblauchzehe

**Fleisch**
60 g Pancetta (2 mm dicke Scheiben, ersatzweise durchwachsener Speck)

**Nudeln/Saucen**
200 g Girandole (Kochzeit: 6 min)
200 ml passierte Tomaten

**sonstiges**
Parmesan


== Kommentar

Pancetta kann weggelassen werden

50 ml passierte Toamten könnne durch Sahne ersetzt werden

<<<

== Rezept



== Bilder

ifdef::ebook-format-epub3[]
image::{site-baseurl}/images/{epub-picture}["{doctitle}"]
endif::ebook-format-epub3[]
ifndef::ebook-format-epub3[]
{% if page.gallery.size == 1 %}
image::{site-baseurl}/images/{{ page.gallery[0].url }}[title="{doctitle}", role="image-popup", link="{site-baseurl}/images/{{ page.gallery[0].url }}"]
{% else %}
++++
{% include gallery  caption=page.title %}
++++
{% endif %}
endif::ebook-format-epub3[]
