= Spaghetti mit Zwiebeln und Rindfleisch
:page-layout: single
:page-categories: ["one-pot-pasta"]
:page-tags: ["pasta", "fleisch", "asiatisch"]
:page-gallery: spaghetti-mit-zwiebeln-und-rindfleisch.jpg
:epub-picture: spaghetti-mit-zwiebeln-und-rindfleisch.jpg
:page-liquid:

**Quelle**: One Pot Pasta, S. 30

**Zubereitungszeit**: 35 min

**Personen**: 2


== Zutaten
:hardbreaks:

**Gemüse/Obst/frische Gewürze**
10 g Ingwer
4 Frühlingszwiebeln
1 Handvoll Koriander
1 Knoblauchzehe
200 g rote Zwiebeln

**Fleisch**
200 g Rinder-Minutensteak

**Nudeln/Saucen**
200 g Spaghetti (Kochzeit: 9 Min.)

**sonstiges**
5 EL Teriyakisauce
1 EL crunchy Erdnussbutter
3 EL Limettensaft
700 ml Fleischbrühe
2 EL Röstzwiebeln

== Kommentar

Alternativ: 1 Hähnchenbrustfilet (von Anfang mitkochen) oder ca. 150 g rohe, geschälte Garnelen (letzten 3 Minuten) anstelle von Rindfleisch

<<<

== Rezept



== Bilder

ifdef::ebook-format-epub3[]
image::{site-baseurl}/images/{page-gallery}["{doctitle}"]
endif::ebook-format-epub3[]
ifndef::ebook-format-epub3[]
{% if page.gallery.size == 1 %}
image::{site-baseurl}/images/{{ page.gallery[0].url }}["{doctitle}", role="image-popup", link="{site-baseurl}/images/{{ page.gallery[0].url }}"]
{% else %}
++++
{% include gallery  caption=page.title %}
++++
{% endif %}
endif::ebook-format-epub3[]
